services:
  app:
    image: docker.io/eclipse-temurin:21-jdk
    container_name: java_app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/alura_series
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    command: ./gradlew bootRun
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.io/postgres:16
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=alura_series
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d alura_series" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
