# Application
spring.application.name=screenmatch
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
# Se a variável DB_HOST não existir (rodando local), assume 'localhost'
# Se rodar dentro do Docker completo, o Spring receberá 'db' ou 'postgres' como host
# Database
app.database.host=${DB_HOST:localhost}
app.database.port=${DB_PORT:5432}
app.database.name=${DB_NAME}
app.database.username=${DB_USERNAME}
app.database.password=${DB_PASSWORD}
app.apiKey=${API_KEY}
app.apiUrl=${OMDB_API_URL}

# DataSource
spring.datasource.url=jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}
spring.datasource.username=${app.database.username}
spring.datasource.password=${app.database.password}
